name: 'Bazel Build Workflows'
on: [push]
jobs:
  build_code:
    name: 'Build code'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code onto runner'
        uses: actions/checkout@v2 # https://github.com/marketplace/actions/checkout

      - name: 'Bazel Build'
        run: ./utilities/pipeline.sh bazel_build

      - name: 'Bazel Test'
        run: ./utilities/pipeline.sh unit_test

      - name: 'Code Coverage'
        run: ./utilities/pipeline.sh code_coverage